# Använd denna format för Supabase connection pooler
spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.iycfytmnopmfmboaqghm
spring.datasource.password=DavidTommysDatabas1

# Lägg till dessa SSL-inställningar
spring.datasource.hikari.ssl=true
spring.datasource.hikari.sslmode=require